name: Deploy Application

on:
  push:
     branches:
       - "master"

jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile CSS and javascript
        run: |
          npm install 
          npm run prod