name: Deploy Application

on:
  push:
     branches:
       - "master"

jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile CSS and javascript
        run: |
          npm install 
          npm run prod

      - name: Configure PHP 7.3.28
        uses: fahad954/setup-php@master
        with:
          php-version: 7.3.28
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml    